version: "3"
services:
  imagemagick:
    # build: ./docker
    image: docker.pkg.github.com/aazw/pdf-to-pngs-docker/pdf2pngs:latest
    volumes:
    - "./workspace:/workspace"
    environment:
    - "INPUT_FILENAME=hogehoge"
    - "OUTPUT_FILENAME_TEMP=_%03d"
    - "DENSITY=200"
    - "QUALITY=100"
